HOST: http://random-gamification.com

--- Magnificent Monocle Gamification Provider ---
---
API v0.0.1

Star (*) indicates a mandatory request parameter.
---

--
Applications
The following section relates to the application resource.

(Possible: list, register)
--
Get applications registered on the server.

*Resource may only be used by API_KEY for Super-Admin console.*
GET /applications
> Authorization: $API_KEY
< 200
< Content-Type: application/json
{
	[
		{
			"application_id":<OID>,
			"site":<String>,
			"callback":<String>,
			"createdAt":<Date>,
			"admin":<String>,
			"statistics":
			{
				"user_count":<Integer>,
				"event_count":<Integer>,
				"badge_count":<Integer>,
				"rule_count":<Integer>
			}
		}
	]
}
+++++
< 401
< Content-Type: application/json
{ "error":"error", "stats":"Access denied." }

Get application information.
GET /applications/:appid
> Authorization: $API_KEY
< 200
< Content-Type: application/json
{
	"application_id":<OID>,
	"site":<String>,
	"callback":<String>,
	"createdAt":<Date>,
	"admin":<String>,
	"statistics":
	{
		"user_count":<Integer>,
		"event_count":<Integer>
		"badge_count":<Integer>,
		"rule_count":<Integer>
	}
}
+++++
< 404
< Content-Type: application/json
{ "status":"error", "message":"Resource not found." }
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied." }

Register a new application
POST /applications
> Content-Type: application/json
{
	"site":<String>,
	"callback":<String>,
	"admin":<String>
}
< 201
< Content-Type: application/json
{ 
	"status":"success", 
	"message":"Successfully registered.",
	"payload":
	{
		"api_key":<String>,
		"secret_key":<String>
	}
}
+++++
< 409
< Content-Type: application/json
{ "status":"error", "message":"Application cannot be created." }

--
Leaderboard
(Possible: list)

TODO
--

TODO
GET /applications/:appid/leaderboard
> Authorization: $API_KEY
< 200
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

--
Users
(Possible: list, specific, add, modify, delete)

TODO
--
Get the list of all users in the applications
GET /applications/:appid/users
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{
  [
    {
    "user_id":"id",
    "login":"login",
    "firstname":"firstname",
    "lastname":"lastname",
    "email":"email"
    }
  ]
}
+++++
< 401
< Content-Type: text/plain
{TODO}

Get the informations about a specific user
GET /applications/:appid/users/:userid
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{
 "user_id":"id",
 "login":"login",
 "firstname":"firstname",
 "lastname":"lastname",
 "email":"email"
}
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied" }
+++++
< 404
< Content-Type: application/json
{ "status":"error", "message":"Ressource not found" }


Get all badges of a specific user
GET /applications/:appid/users/:userid/badges
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}
+++++
< 404
< Content-Type: application/json
{ "status":"error", "message":"Ressource not found" }

Add a new user in the application
POST /applications/:appid/users
> Content-type: application/json
{TODO}
< 201
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}
+++++
< 405
< Content-Type: text/plain
{TODO}

Update the informations of a users
PUT /applications/:appid/users/:userid
{TODO}
< 204
+++++
< 404
< Content-Type: text/plain
{TODO}

Delete a user from the application
DELETE /applications/:appid/users/:userid
< 204
+++++
< 404
< Content-Type: text/plain
{TODO}


--
Events

All operations related to the event management are in this section. Everything that has to be monitored by the gamification platform is recorded as an event and has to be posted to the gamificatio API.

(Possible: list, specific, add)
--

Gets the list of all events registered on the gamification server for the appid.

This function may only be used by API_KEY for Super-Admin console.

GET /applications/:appid/events
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{
 [
  {
   "event_id":"id",
   "type":"type",
   "user":"user",
   "issued":"date"
  }
 ]
}
+++++
< 401
< Content-Type: text/plain
{ "status":"error", "message":"Access denied" }

Get detailed information about a specific event identified by eventid
GET /applications/:appid/events/:eventid
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{
 "event_id":"id",
 "type":"type",
 "user":"user",
 "issued":"date"
}
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied" }
+++++
< 404
< Content-Type: application/json
{ "status":"error", "message":"Ressource not found" }


Register a new event on the gamification platform for your application
POST /applications/:appid/events
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
> Content-Type: application/json
{
 "type":"type",
 "user":"user"
}
< 201
< Content-Type: application/json
{ "status":"success", "message":"Successfully added" }
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied" }





--
Event Types

All events that are recorded by the gamification API are associated with a type. The types can be defined by the application using the API with the related API calls. Then event types will be used in rules to define the conditions needed to obtain a badge.

(Possible: list, specific, add)
--


Get the list of all types define for this application id.
GET /applications/:appid/types
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{
 [
  {
   "type_id":"id",
   "name":"name"
  }
 ]
}
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied" }


Get information about a specific type id
GET /applications/:appid/types/:type_id
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
< 200
< Content-Type: application/json
{
 [
  {
   "type_id":"id",
   "name":"name"
  }
 ]
}
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied" }
+++++
< 404
< Content-Type: application/json
{ "status":"error", "message":"Ressource not found" }


Add a new event type in the application
POST /applications/:appid/types
> Timestamp: timestamp
> Signature: signature
> Signature-Method: HMAC-SHA1
> Authorization: api_key
> Content-Type: application/json
{
 [
  {
   "name":"name"
  }
 ]
}
< 201
< Content-Type: application/json
{ "status":"success", "message":"Successfully added" }
+++++
< 401
< Content-Type: application/json
{ "status":"error", "message":"Access denied" }


--
Rules
(Possible: list, specific, add, modify?, delete?)

TODO
--

TODO
GET /applications/:appid/rules
< 200
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
GET /applications/:appid/rules/:ruleid
< 200
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
POST /applications/:appid/rules
< 201
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
PUT /applications/:appid/rules/:ruleid
< 204
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
DELETE /applications/:appid/rules/:ruleid
< 204
+++++
< 401
< Content-Type: text/plain
{TODO}

--
Badges
(Possible: list, specific, add, modify?)

TODO
--

TODO
GET /applications/:appid/badges
< 200
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
GET /applications/:appid/badges/:badgeid
< 200
< Content-Type: application/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
POST /applications/:appid/badges
< 201
< Content-Type: applications/json
{TODO}
+++++
< 401
< Content-Type: text/plain
{TODO}

TODO
PUT /applications/:appid/badges/:badgeid
< 204
+++++
< 401
< Content-Type: text/plain
{TODO}

